[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\	"_": {
\		"runner": "vimproc",
\		"runner/vimproc/updatetime": 60,
\		"outputter/buffer/split": ":botright 8sp",
\		"outputter/buffer/close_on_empty": 1
\	},
\}
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_exclude_preview=1
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

#[[plugins]]
#repo = 'vim-scripts/fcitx.vim'
